name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11","3.12"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint autopep8 pyflakes
    - name: Create post_traces directory
      run: mkdir -p post_traces
    - name: Run autopep8 and save trace
      run: autopep8 --in-place --recursive . > post_traces/autopep8_trace.txt 2>&1
    - name: Run pylint and save trace
      run: pylint $(git ls-files '*.py') > post_traces/pylint_trace.txt 2>&1 || true
    - name: Run pyflakes and save trace
      run: pyflakes . > post_traces/pyflakes_trace.txt 2>&1 || true
    - name: Upload trace files
      uses: actions/upload-artifact@v4
      with:
        name: post-traces
        path: post_traces
    - name: Commit changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add post_traces
        git commit -am "Apply autopep8 formatting and add tool traces" || echo "No changes to commit"
        git push
